version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app