name: cicd
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: ssh
    ssh root@103.245.39.44
    cd daud-erlangga/test_js
    docker compose down
    docker compose up